package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubeIoT/api-docs/models"
)

/*DeleteDeviceIDNoContent Device was Deleted

swagger:response deleteDeviceIdNoContent
*/
type DeleteDeviceIDNoContent struct {
}

// NewDeleteDeviceIDNoContent creates DeleteDeviceIDNoContent with default headers values
func NewDeleteDeviceIDNoContent() *DeleteDeviceIDNoContent {
	return &DeleteDeviceIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteDeviceIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*DeleteDeviceIDNotFound Device was not found

swagger:response deleteDeviceIdNotFound
*/
type DeleteDeviceIDNotFound struct {
	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteDeviceIDNotFound creates DeleteDeviceIDNotFound with default headers values
func NewDeleteDeviceIDNotFound() *DeleteDeviceIDNotFound {
	return &DeleteDeviceIDNotFound{}
}

// WithPayload adds the payload to the delete device Id not found response
func (o *DeleteDeviceIDNotFound) WithPayload(payload *models.Error) *DeleteDeviceIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete device Id not found response
func (o *DeleteDeviceIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeviceIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
