package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubeIoT/api-docs/models"
)

/*PostDeviceCreated User was created

swagger:response postDeviceCreated
*/
type PostDeviceCreated struct {
	/*
	  In: Body
	*/
	Payload *models.Device `json:"body,omitempty"`
}

// NewPostDeviceCreated creates PostDeviceCreated with default headers values
func NewPostDeviceCreated() *PostDeviceCreated {
	return &PostDeviceCreated{}
}

// WithPayload adds the payload to the post device created response
func (o *PostDeviceCreated) WithPayload(payload *models.Device) *PostDeviceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post device created response
func (o *PostDeviceCreated) SetPayload(payload *models.Device) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDeviceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
