package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDeviceIDCapabilitiesHandlerFunc turns a function with the right signature into a post device ID capabilities handler
type PostDeviceIDCapabilitiesHandlerFunc func(PostDeviceIDCapabilitiesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDeviceIDCapabilitiesHandlerFunc) Handle(params PostDeviceIDCapabilitiesParams) middleware.Responder {
	return fn(params)
}

// PostDeviceIDCapabilitiesHandler interface for that can handle valid post device ID capabilities params
type PostDeviceIDCapabilitiesHandler interface {
	Handle(PostDeviceIDCapabilitiesParams) middleware.Responder
}

// NewPostDeviceIDCapabilities creates a new http.Handler for the post device ID capabilities operation
func NewPostDeviceIDCapabilities(ctx *middleware.Context, handler PostDeviceIDCapabilitiesHandler) *PostDeviceIDCapabilities {
	return &PostDeviceIDCapabilities{Context: ctx, Handler: handler}
}

/*PostDeviceIDCapabilities swagger:route POST /device/{id}/capabilities device postDeviceIdCapabilities

Creates new capability on device

*/
type PostDeviceIDCapabilities struct {
	Context *middleware.Context
	Handler PostDeviceIDCapabilitiesHandler
}

func (o *PostDeviceIDCapabilities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostDeviceIDCapabilitiesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil {
		// bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
