package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/go-openapi/strfmt"

	"github.com/kubeIoT/api-docs/models"
)

// NewPutDeviceIDCapabilitiesParams creates a new PutDeviceIDCapabilitiesParams object
// with the default values initialized.
func NewPutDeviceIDCapabilitiesParams() PutDeviceIDCapabilitiesParams {
	var ()
	return PutDeviceIDCapabilitiesParams{}
}

// PutDeviceIDCapabilitiesParams contains all the bound params for the put device ID capabilities operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutDeviceIDCapabilities
type PutDeviceIDCapabilitiesParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: body
	*/
	Body *models.DeviceCapability
	/*
	  Required: true
	  In: query
	*/
	CapID int64
	/*
	  Required: true
	  In: path
	*/
	ID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PutDeviceIDCapabilitiesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.DeviceCapability
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	qCapID, qhkCapID, _ := qs.GetOK("capId")
	if err := o.bindCapID(qCapID, qhkCapID, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutDeviceIDCapabilitiesParams) bindCapID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("capId", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("capId", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("capId", "query", "int64", raw)
	}
	o.CapID = value

	return nil
}

func (o *PutDeviceIDCapabilitiesParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}
