package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubeIoT/api-docs/models"
)

/*PutDeviceIDNoContent Device was updated

swagger:response putDeviceIdNoContent
*/
type PutDeviceIDNoContent struct {
}

// NewPutDeviceIDNoContent creates PutDeviceIDNoContent with default headers values
func NewPutDeviceIDNoContent() *PutDeviceIDNoContent {
	return &PutDeviceIDNoContent{}
}

// WriteResponse to the client
func (o *PutDeviceIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*PutDeviceIDNotFound Device was not found

swagger:response putDeviceIdNotFound
*/
type PutDeviceIDNotFound struct {
	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutDeviceIDNotFound creates PutDeviceIDNotFound with default headers values
func NewPutDeviceIDNotFound() *PutDeviceIDNotFound {
	return &PutDeviceIDNotFound{}
}

// WithPayload adds the payload to the put device Id not found response
func (o *PutDeviceIDNotFound) WithPayload(payload *models.Error) *PutDeviceIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device Id not found response
func (o *PutDeviceIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
