package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubeIoT/api-docs/models"
)

/*PutDeviceIDCapabilitiesNoContent Device capability was updated

swagger:response putDeviceIdCapabilitiesNoContent
*/
type PutDeviceIDCapabilitiesNoContent struct {
}

// NewPutDeviceIDCapabilitiesNoContent creates PutDeviceIDCapabilitiesNoContent with default headers values
func NewPutDeviceIDCapabilitiesNoContent() *PutDeviceIDCapabilitiesNoContent {
	return &PutDeviceIDCapabilitiesNoContent{}
}

// WriteResponse to the client
func (o *PutDeviceIDCapabilitiesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*PutDeviceIDCapabilitiesNotFound Device was not found

swagger:response putDeviceIdCapabilitiesNotFound
*/
type PutDeviceIDCapabilitiesNotFound struct {
	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutDeviceIDCapabilitiesNotFound creates PutDeviceIDCapabilitiesNotFound with default headers values
func NewPutDeviceIDCapabilitiesNotFound() *PutDeviceIDCapabilitiesNotFound {
	return &PutDeviceIDCapabilitiesNotFound{}
}

// WithPayload adds the payload to the put device Id capabilities not found response
func (o *PutDeviceIDCapabilitiesNotFound) WithPayload(payload *models.Error) *PutDeviceIDCapabilitiesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device Id capabilities not found response
func (o *PutDeviceIDCapabilitiesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceIDCapabilitiesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
