package capability

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteCapabilityIDNoContent capability was Deleted

swagger:response deleteCapabilityIdNoContent
*/
type DeleteCapabilityIDNoContent struct {
}

// NewDeleteCapabilityIDNoContent creates DeleteCapabilityIDNoContent with default headers values
func NewDeleteCapabilityIDNoContent() *DeleteCapabilityIDNoContent {
	return &DeleteCapabilityIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteCapabilityIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
