package capability

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PutCapabilityIDNoContent capability was updated

swagger:response putCapabilityIdNoContent
*/
type PutCapabilityIDNoContent struct {
}

// NewPutCapabilityIDNoContent creates PutCapabilityIDNoContent with default headers values
func NewPutCapabilityIDNoContent() *PutCapabilityIDNoContent {
	return &PutCapabilityIDNoContent{}
}

// WriteResponse to the client
func (o *PutCapabilityIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
