package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kubeIoT/api-docs/models"
)

/*PostApplicationCreated Application was created

swagger:response postApplicationCreated
*/
type PostApplicationCreated struct {
	/*
	  In: Body
	*/
	Payload *models.Application `json:"body,omitempty"`
}

// NewPostApplicationCreated creates PostApplicationCreated with default headers values
func NewPostApplicationCreated() *PostApplicationCreated {
	return &PostApplicationCreated{}
}

// WithPayload adds the payload to the post application created response
func (o *PostApplicationCreated) WithPayload(payload *models.Application) *PostApplicationCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post application created response
func (o *PostApplicationCreated) SetPayload(payload *models.Application) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostApplicationCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
