package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PutApplicationIDNoContent Application was updated

swagger:response putApplicationIdNoContent
*/
type PutApplicationIDNoContent struct {
}

// NewPutApplicationIDNoContent creates PutApplicationIDNoContent with default headers values
func NewPutApplicationIDNoContent() *PutApplicationIDNoContent {
	return &PutApplicationIDNoContent{}
}

// WriteResponse to the client
func (o *PutApplicationIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*PutApplicationIDNotFound Application was not found

swagger:response putApplicationIdNotFound
*/
type PutApplicationIDNotFound struct {
}

// NewPutApplicationIDNotFound creates PutApplicationIDNotFound with default headers values
func NewPutApplicationIDNotFound() *PutApplicationIDNotFound {
	return &PutApplicationIDNotFound{}
}

// WriteResponse to the client
func (o *PutApplicationIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
