package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteUserIDNoContent Person was Deleted

swagger:response deleteUserIdNoContent
*/
type DeleteUserIDNoContent struct {
}

// NewDeleteUserIDNoContent creates DeleteUserIDNoContent with default headers values
func NewDeleteUserIDNoContent() *DeleteUserIDNoContent {
	return &DeleteUserIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteUserIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
