package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PutUserIDNoContent Person was updated

swagger:response putUserIdNoContent
*/
type PutUserIDNoContent struct {
}

// NewPutUserIDNoContent creates PutUserIDNoContent with default headers values
func NewPutUserIDNoContent() *PutUserIDNoContent {
	return &PutUserIDNoContent{}
}

// WriteResponse to the client
func (o *PutUserIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
