package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteImageIDNoContent Image was Deleted

swagger:response deleteImageIdNoContent
*/
type DeleteImageIDNoContent struct {
}

// NewDeleteImageIDNoContent creates DeleteImageIDNoContent with default headers values
func NewDeleteImageIDNoContent() *DeleteImageIDNoContent {
	return &DeleteImageIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteImageIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}
