package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetImageIDHandlerFunc turns a function with the right signature into a get image ID handler
type GetImageIDHandlerFunc func(GetImageIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetImageIDHandlerFunc) Handle(params GetImageIDParams) middleware.Responder {
	return fn(params)
}

// GetImageIDHandler interface for that can handle valid get image ID params
type GetImageIDHandler interface {
	Handle(GetImageIDParams) middleware.Responder
}

// NewGetImageID creates a new http.Handler for the get image ID operation
func NewGetImageID(ctx *middleware.Context, handler GetImageIDHandler) *GetImageID {
	return &GetImageID{Context: ctx, Handler: handler}
}

/*GetImageID swagger:route GET /image/{id} image getImageId

Details of image

*/
type GetImageID struct {
	Context *middleware.Context
	Handler GetImageIDHandler
}

func (o *GetImageID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetImageIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil {
		// bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
