package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostImageParams creates a new PostImageParams object
// with the default values initialized.
func NewPostImageParams() PostImageParams {
	var ()
	return PostImageParams{}
}

// PostImageParams contains all the bound params for the post image operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostImage
type PostImageParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostImageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
