package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Capability capability
// swagger:model capability
type Capability struct {
	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// Name of the peripheral device
	PeripherialDevice string `json:"peripherial_device,omitempty"`

	// Communication protocol of capability
	Protocol string `json:"protocol,omitempty"`
}

// Validate validates this capability
func (m *Capability) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
