package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DeviceCapability device capability
// swagger:model device_capability
type DeviceCapability struct {
	// app id
	AppID int64 `json:"app_id,omitempty"`

	// The bus on device where the capability is connected
	// Format cannot be currently specified, we don't know yet
	// how the connection to peripheral will look like
	//
	BusConnection string `json:"bus_connection,omitempty"`

	// Id to capability type
	CapID int64 `json:"cap_id,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Is the capability used by application
	Used bool `json:"used,omitempty"`
}

// Validate validates this device capability
func (m *DeviceCapability) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
