package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Event event
// swagger:model event
type Event struct {
	// event message
	EventMessage string `json:"event_message,omitempty"`

	// event timestamp
	EventTimestamp string `json:"event_timestamp,omitempty"`

	// event type
	EventType string `json:"event_type,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Id of owner of event
	//
	ParentID int64 `json:"parent_id,omitempty"`
}

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
