package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Image image
// swagger:model image
type Image struct {
	// base image
	BaseImage string `json:"base_image,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// Ports exposed by application
	ExposedPorts []string `json:"exposed_ports"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// required capabilities
	RequiredCapabilities []int64 `json:"required_capabilities"`
}

// Validate validates this image
func (m *Image) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExposedPorts(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRequiredCapabilities(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Image) validateExposedPorts(formats strfmt.Registry) error {

	if swag.IsZero(m.ExposedPorts) {
		// not required
		return nil
	}

	return nil
}

func (m *Image) validateRequiredCapabilities(formats strfmt.Registry) error {

	if swag.IsZero(m.RequiredCapabilities) {
		// not required
		return nil
	}

	return nil
}
