package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// User User in system
// swagger:model user
type User struct {
	// account created
	AccountCreated string `json:"account_created,omitempty"`

	// devices
	Devices []int64 `json:"devices"`

	// email
	Email string `json:"email,omitempty"`

	// email verified
	EmailVerified bool `json:"email_verified,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// last logged in
	LastLoggedIn string `json:"last_logged_in,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDevices(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) validateDevices(formats strfmt.Registry) error {

	if swag.IsZero(m.Devices) {
		// not required
		return nil
	}

	return nil
}
